#!/bin/bash

clear
echo "==============================="
echo " Clementinose Terminal Menu"
echo "==============================="
echo ""
echo "1) LXC SSH setup"
echo "2) Proxmox SSH setup"
echo "3) Exit"
echo ""

read -p "Välj ett alternativ: " choice

PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINr2Lm9pY8GLLgaPvmD+kbNKsQdJuKdHfa6amveI4xFL Generated By Termius"

case "$choice" in
  1)
    echo "▶ Kör LXC SSH setup..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/lxc-ssh/main/init.sh) "$PUBKEY"
    ;;
  2)
    echo "▶ Kör Proxmox SSH setup..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-ssh-setup/main/init-proxmox.sh) "$PUBKEY"
    ;;
  3)
    echo "👋 Hej då"
    exit 0
    ;;
  *)
    echo "❌ Fel val"
    ;;
esac
