#!/bin/bash

clear
echo "==============================="
echo " Clementinose Terminal Menu"
echo "==============================="
echo ""
echo "1) LXC SSH setup"
echo "2) Proxmox SSH setup"
echo "3) Node Power Monitor"
echo "4) Exit"
echo ""

read -p "Välj ett alternativ: " choice

PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINr2Lm9pY8GLLgaPvmD+kbNKsQdJuKdHfa6amveI4xFL Generated By Termius"

case "$choice" in
  1)
    echo "▶ Kör LXC SSH setup..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/lxc-ssh/main/init.sh) "$PUBKEY"
    ;;
  2)
    echo "▶ Kör Proxmox SSH setup..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-ssh-setup/main/init-proxmox.sh) "$PUBKEY"
    ;;
  3)
    echo "▶ Kör Node Power Monitor..."
    # Visa hostname och IP
    HOSTNAME=$(hostname)
    IP=$(hostname -I | awk '{print $1}')
    echo "==============================="
    echo "🔌 Proxmox Node Power Monitor"
    echo "🖥️ Hostname: $HOSTNAME"
    echo "🌐 IP: $IP"
    # Simulerad strömförbrukning (eller ersätt med ipmitool/upower om du vill)
    POWER_W=$(shuf -i 50-250 -n 1)
    echo "⚡ Strömförbrukning: $POWER_W W"
    echo "==============================="
    ;;
  4)
    echo "👋 Hej då"
    exit 0
    ;;
  *)
    echo "❌ Fel val"
    ;;
esac
